# Generated by Django 4.2.6 on 2024-02-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='auction_item_images/'),
        ),
    ]
